# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'VayeApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for VayeApp
  pod 'RealmSwift'
  target 'VayeAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'VayeAppUITests' do
    # Pods for testing
  end

end
